### ISSUE TITLE
Successful downloaded reported by app but where is the file?

### ISSUE THREAD

**Issue by garfieldbanks** [s8sachin/subtitler#9]
Successful downloaded reported by app but where is the file?

I have no idea where the file was put after being downloaded.

**Comment by s8sachin** [comment]
downloaded sub file will be in the same directory of video file, under the same video file name.

**Comment by garfieldbanks** [comment]
The download fails then because the folder I'm getting it from is read-only. Feature request: add option to specify download location.

**Comment by s8sachin** [comment]
Interesting and valid, will consider in next update !
